<a href="https://colab.research.google.com/github/sachin886x/deep-learning-lab/blob/main/lab1_dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# 1D
t1 = torch.tensor([1, 2, 3])
n1 = np.array([1, 2, 3])

# 2D
t2 = torch.tensor([[1, 2], [3, 4]])
n2 = np.array([[1, 2], [3, 4]])

# 3D
t3 = torch.randn(2, 3, 4)
n3 = np.random.randn(2, 3, 4)


In [ ]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

a + b        # addition
a - b        # subtraction
a * b        # multiplication
a / b        # division


tensor([0.2500, 0.4000, 0.5000])

In [ ]:
a_np = np.array([1., 2., 3.])
b_np = np.array([4., 5., 6.])

a_np + b_np
a_np - b_np
a_np * b_np
a_np / b_np


array([0.25, 0.4 , 0.5 ])

In [ ]:
# Dot product (1D)
torch.dot(a, b)
np.dot(a_np, b_np)

# Matrix multiplication
A = torch.randn(2, 3)
B = torch.randn(3, 4)
torch.matmul(A, B)      # or A @ B

A_np = np.random.randn(2, 3)
B_np = np.random.randn(3, 4)
A_np @ B_np


array([[ 1.22668403,  0.54055908, -1.04687396, -1.00839002],
       [-0.55638138, -0.74568124,  0.92847171,  0.8643262 ]])

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

x[0]          # first row
x[:, 1]       # second column
x[0, 1]       # element

# Boolean masking
mask = x > 3
x[mask]       # elements > 3

# Subtensor
x[:2, :2]


tensor([[1, 2],
        [4, 5]])

In [ ]:
x_np = np.array([[1, 2, 3],
                 [4, 5, 6]])
x_np[x_np > 3]


array([4, 5, 6])

In [ ]:
t = torch.arange(6)

t.view(2, 3)          # only works if contiguous
t.reshape(2, 3)      # safer

t.unsqueeze(0)        # add dim at axis 0 -> (1, 6)
t.unsqueeze(1)        # -> (6, 1)

t2 = torch.tensor([[1, 2, 3]])
t2.squeeze()          # removes size-1 dims


tensor([1, 2, 3])

In [ ]:
n = np.arange(6)
n.reshape(2, 3)       # same idea, always safe


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
A = torch.randn(3, 4)
b = torch.randn(4)

A + b     # b broadcast to (3, 4)


tensor([[-1.2564,  0.4361, -0.2208, -0.5476],
        [ 1.3290, -0.6127, -0.1110, -0.3940],
        [ 1.9090, -0.9316, -0.6669,  0.0465]])

In [ ]:
A_np = np.random.randn(3, 4)
b_np = np.random.randn(4)
A_np + b_np


array([[-0.54202054,  0.47582604,  0.98691445, -0.68307734],
       [-0.61008624,  2.17604014,  0.98622999,  0.8165943 ],
       [-1.45412114, -1.59181393,  0.24523349, -0.18647102]])

In [ ]:
x = torch.tensor([1., 2., 3.])

y = x + 1      # out-of-place (new tensor)
x.add_(1)      # in-place (modifies x)


tensor([2., 3., 4.])

In [ ]:
x_np = np.array([1., 2., 3.])
y_np = x_np + 1     # out-of-place
x_np += 1           # in-place
